project:
  type: book

execute:
  freeze: auto

book:
  title: "SpatialOmics CODEX analysis"
  author: "Paul Marcoux"
  chapters:
    - index.qmd
    - CODEX_Nathalie_test_1_analysis.qmd
    - CODEX_Nathalie_test_2_analysis.qmd

format:
  html:
    theme: cosmo